### ISSUE TITLE
Package libjpeg9-dev is not available

### ISSUE THREAD

**Issue by KaiWalter** [erkrystof/vice#2]
On this line

<https://github.com/erkrystof/vice/blob/5e29dcddcd429e33c167b28e5ea8b1941550b9d8/install-vice-3.6.1-buster-raspi-4.sh#L73>

I get

```
Package libjpeg9-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev:armhf libjpeg62-turbo-dev

E: Package 'libjpeg9-dev' has no installation candidate
```

Hence I replaced the line with `sudo apt-get install -y libjpeg62-turbo-dev:armhf libjpeg62-turbo-dev`.

## config

**Raspberry Pi 400**

```
>lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by erkrystof** [comment]
Thanks, @KaiWalter !  I'm going to bench test this on my RPI and I'll make an update soon.
